{{- if .Values.rbac -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leanix-k8s-connector
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "leanix-k8s-connector.labels" . | indent 4 }}
{{- end -}}